config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get '/post-idea', to: 'pages#post_idea', as: :post_idea
  get '/about', to: 'pages#about', as: :about
  get '/give-feedback', to: 'pages#give_feedback', as: :give_feedback
  get '/login', to: 'pages#login', as: :login
  
  get '/help', to: 'pages#help', as: :help
  get '/help/idea-safety', to: 'pages#idea_safety', as: :idea_safety
  get '/help/tips-for-video-pitch', to: 'pages#tips_for_video', as: :tips_for_video
  get '/help/before-you-post', to: 'pages#before_you_post', as: :before_you_post
  
  get '/contact-customer-care', to: 'pages#contact_customer_care', as: :contact_customer_care
  get '/terms', to: 'pages#terms', as: :terms
  get '/privacy', to: 'pages#privacy', as: :privacy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

  def post_idea
  end

  def about
  end

  def give_feedback
  end
  
  def contact_customer_care
  end
  
  def help
  end
  
  def idea_safety
  end
  
  def tips_for_video
  end
  
  def before_you_post
  end
  
  def terms
  end
  
  def privacy
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title MountDream
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{:href => "https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800", :rel => "stylesheet", :type => "text/css"}/
  %body
    = render 'shared/header'
    = yield
    = render 'shared/footer'

app/views/pages/about.html.haml
.about-masthead
  .container
    %h1 About us
    %p I think it’s important to take as much feedback as you can from as many people as you can for whatever idea you have.
    %b - Elon Musk

.text-center
  %ul.about-navbar.list-inline
    %li= link_to "What is Mount Dream", "#", class: "what-is active"
    %li= link_to "Mission", "#", class: "mission"
    %li= link_to "Business Philosophy", "#", class: "philosophy"
    %li= link_to "Culture and Values", "#", class: "culture"
    %li= link_to "Our Story and Team", "#", class: "story"

= render "pages/about/what_is"
= render "pages/about/mission"
= render "pages/about/philosophy"
= render "pages/about/culture_and_values"
= render "pages/about/our_story"

.section-cta.text-center
  .container
    %h1 Pursue your dream, intelligently. 
    %h2 Start getting feedback now.
    = link_to "Post your idea", post_idea_path, class: "btn uppercase bold"
    = link_to "Contact customer care", contact_customer_care_path, class: "btn default uppercase bold"

app/views/pages/about/_culture_and_values.html.haml
.about-culture-wrapper.about-tab
  .about.about-culture.text-center
    .container
      %h1 Culture & Values
      
      %h3 Mount Dream’s network is different from other networks on the web.
      
      .text-left
        %p Many networks thrive on controversy, negativity, and disputes between users. While creating controversy can help generate page views, our goal is different. Let's skip the arguments and insults — we’re a place where users can exchange ideas without all the drama.
        
      %h3 Our Single Core Value: Genuinely help others.

      .text-left
        %p Having a pure and worthy motive to help the people around you is the heart and soul of Mount Dream. This applies to our team, our network, and partners.
        %p Keeping in mind that sometimes, when giving feedback, the best way you can genuinely help someone is by telling them — respectfully — what you don’t like about their idea. 
        %p We believe that a network founded on this value is where people can flourish and reach their fullest potential, overcome their fears, and gain the courage to act. 
      

app/views/pages/about/_mission.html.haml
.about-mission-wrapper.about-tab
  .about.about-mission.text-center
    .container
      %h1 Mission
      %h3
        To help as many people as possible pursue their dream
        %br.visible-md.visible-lg/
        of starting a successful business.
        
      .text-left
        %p There are examples all around you of people with no prior experience who turned their idea into a million dollar business. Why&nbsp;can’t you be next?
        %p After spending time on Mount Dream, we want to open your eyes to the fact that you are no different than many people who have turned their dreams into a reality -- and now you have powerful tools and resources to improve your chances of success.
        
        .well
          %p “Whether you think you can, or you think you can’t, you’re right.”
          %span — Henry Ford, founder of Ford Motor Company

        %p
          Need help turning your idea into a business? We’ll offer you some free advice. Email #{mail_to "help@mountdream.com"}.
          
          

app/views/pages/about/_our_story.html.haml
.about-story-wrapper.about-tab
  .about.about-story.text-center
    .container
      %h1 Our Story and Team
      
      .text-left
        %p
          After graduating Babson College in 2009,
          = link_to "highly rated", "http://www.babson.edu/news-events/babson-news/Pages/us-news-and-world-report-ranks-babson-no-1-for-entrepreneurship.aspx"
          for entrepreneurship, Michael Markarian noticed something odd.
        %p Many classmates and friends who believed in business or product ideas were not following through on their ideas and dreams. When considering why, he realized that in most cases, the common reasons for not getting started were not the real reasons that people were getting stuck.
        %br/

        %ol
          %li
            %span Not having enough money.
            They had money or could get the money if they were really committed. Plus, many ideas didn’t require much money to get started.
          %li
            %span Not having enough time.
            Sure, we are all busy, but less TV or social media would mean more free time to begin seeing if your idea is viable.
          %li
            %span Not having the knowledge.
            There is a wealth of information available on books and blogs, and many entrepreneurs will give you free advice if you ask the right way.
          %br/
            
        %p After much thought, Markarian realized the primary reason he and his friends were not following through was that they really didn’t know whether or not customers would be interested in their products or services. The feeling of uncertainty left them stuck.
        %p A simple, inexpensive tool to help entrepreneurs quickly connect with customers — instead of just asking friends and family whether they liked the idea — would be probably be valuable.
        
        %h3 Testing the idea
        
        %p Since Mount Dream did not yet exist, Markarian created a simple website using Squarespace. He recorded a video pitch of Mount Dream’s concept on his iPhone, set up a simple survey, and manually sent it out to lots of entrepreneurs he knew (and didn’t know).
        %p The feedback Markarian received opened his eyes to new ideas — and concerns — he never considered, which instantly made the Mount Dream concept stronger. The feedback was also particularly thoughtful, and seemed to be coming from a group of people who genuinely wanted to help. 
        %p At this moment, it was clear that getting quality feedback from potential customers would be extremely helpful to millions of people who want to get their dreams off the ground.
        
        %h3 Next came Kickstarter
        
        %p Funds were needed to build the actual Mount Dream site — Squarespace was fine for a test, but limiting. Markarian did not want to raise capital from investors yet and believed in staying lean until determining a profitable model.
        %p Kickstarter was the perfect next step, and also appropriate considering Mount Dream itself can be used as a pre-crowdfunding tool. Since many future Mount Dream customers would use tools like Kickstarter after Mount Dream, it was important to fully understand these tools and how to get the most value out of them.
        %p
          In December 2014, Mount Dream was funded with $51,070 — at the time, 5th most all-time for a Web project. Here is the video from our campaign (or feel free to
          = link_to "visit the Kickstarter campaign", "https://www.kickstarter.com/projects/1027706210/mount-dream-a-pre-kickstarter-tool-launching-on-ki"
          itself).
        
        .video-wrapper
          <iframe src="https://player.vimeo.com/video/127175589" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        
        %p We learned that Kickstarter is the last step before launching, not the first step many people believe it to be. For success on Kickstarter, there is a lot you need to do first — for instance, develop prototypes, find a manufacturer, create a powerful marketing plan for your campaign, and much more. This all requires time and money, which is why Mount Dream makes sense as a step before Kickstarter or Indiegogo to make sure your idea is worth putting all that effort into.
        
        %h3 Mount Dream: As of today
        
        %p Mount Dream is headquartered in Providence, RI.
        %p With Mount Dream, we now live in a world where procrastination & blind execution (without evidence) should both be things of the past. 
        %p We welcome anyone who wants to take part in bringing Mount Dream to the people who need it, and instilling a real sense of hope and promise for anyone with an idea and a dream.
        %br/
        
        %h4
          Interested in joining us? Email
          = mail_to "careers@mountdream.com"
          for a list of job openings.
        

app/views/pages/about/_philosophy.html.haml
.about-philosophy-wrapper.about-tab
  .about.about-philosophy.text-center
    .container
      %h1 Mount Dream Business Philosophy
      
      .text-left
        %p We encourage everyone to read and share Mount Dream’s business philosophy. Regardless of whether you use Mount Dream, we believe these ten principles can greatly improve your chance of being a successful entrepreneur.
        
        %p The following ten principles are indisputably true and commonly misunderstood by first time entrepreneurs.
        
        %ol.ol-circled.red
          %li
            %span Don’t let statistics discourage you.
            You’ve probably read that 9 out of 10 startups fail. Realize that not everyone has equal work ethic or persistence, and 42% of people fail because they pursue ideas without enough demand. You can improve your odds by following simple principles for success that most people neglect.
          %li
            %span Passion is vital, but not enough.
            Ever watch Shark Tank and see the person who bet the farm on an idea because they “believed” in it? The fact that you are passionate about – or fall in love with – your idea does not necessarily mean that customers are going to buy it.
          %li
            %span Persisting on a bad idea is a bad idea.
            Many entrepreneurs fail before they succeed. The act of “failing” means they stopped working on one idea to arrive at the idea that made them successful. Persist on your journey as an entrepreneur, not necessarily on every idea you pursue.
          %li
            %span Do something useful.
            Customers will exchange their hard-earned money for products and services only if it does something useful for them. No one will buy from you unless they find what you are doing to be useful — or valuable — to them.
          %li
            %span Protect your downside.
            Taking big risks does not make you a great entrepreneur. Most smart entrepreneurs look for ways to limit their exposure if a venture doesn’t work out. For instance, when starting Virgin Airlines, billionaire Richard Branson cut a deal with Boeing that he could return the planes at no further liability if the venture did not take off. You should take a similar approach.
          %li
            %span Customers make you successful, not investors.
            New companies regularly get funded with millions of dollars, and then go out of business. Raising money is sometimes a necessary part of building your business, but it doesn’t make you successful. Having customers buy your products or use your service is the only way to build a strong business.
          %li
            %span Seek expert advice for execution, not validation.
            Avoid asking “experts”: Will this sell? Very few people can speak on behalf of millions of people. Remember that even top investors turned down Google because they doubted they could beat Yahoo. Do ask experts how to find a manufacturer, how to drive traffic to your website, or how to build a great team.
          %li
            %span Ideas are <i>not</i> worthless.
            Many people misunderstand the statement that “ideas are worthless”. This statement is not true. There has never been a successful company in the history of the world that is founded on a bad idea. What is really meant by this statement is “ideas are worthless without execution.” This, of course, is true.
          %li
            %span Great execution does not make up for a bad idea.
            If customers do not want your idea, you will not generate revenue. Without revenue, you generate no cash – and cash is king. You will not be successful with a bad idea.
          %li
            %span A great idea does not make up for poor execution.
            Success requires taking action, on the right idea, in the right way. You must have all three elements. For instance, Uber was not the first company to try to build “Uber”.
          
        %p There is a bonus principle and it’s arguably the most important one of all. If you get this wrong, nothing else matters — you will not succeed.
        
        %h4.form-heading Enter your email in the box below and we will send you the bonus principle.

        .bonus-form
          = render "shared/subscription_form", label: "Get your bonus"
          

app/views/pages/about/_what_is.html.haml
.about-what-is-wrapper.about-tab
  .about.about-what-is.text-center
    .container
      %h1 What is Mount Dream?
      %h4
        Mount&nbsp;Dream gets&nbsp;you unbiased feedback on your&nbsp;business or product&nbsp;idea
        %br.visible-md.visible-lg/
        from potential&nbsp;customers before you invest lots of time and money.
      %h4
        You can
        = link_to "post ideas", post_idea_path
        or you can
        = link_to "give feedback", give_feedback_path

  .section.about-the-old-way.text-center
    .container
      = image_tag "ways.gif", class: "visible-sm visible-md visible-lg visible-xs"

  .section.about-talking-to-customers.text-center
    .container
      %h1
        Talking to customers should be your first step when
        %br.hidden-sm.hidden-xs/
        you have a new idea because:

      .one.row
        .col-xs-7.col-xs-offset-5.col-sm-6.col-sm-offset-6.col-md-4.col-md-offset-8.step
          = image_tag "about_1.png"
          %p
            %span If you don’t, you probably won’t take action or follow-through.
            Isn’t the real reason you aren’t pursuing your idea that you don’t know whether potential customers will respond favorably?

      .two.row
        .col-xs-7.col-sm-6.col-md-4.step
          %p
            %span If you don’t, you risk pursuing a bad idea.
            Your greatest risk as an entrepreneur is falling in love with an idea that customers do not want.
          = image_tag "about_2.png"

      .three.row
        .col-xs-7.col-xs-offset-5.col-sm-6.col-sm-offset-6.col-md-4.col-md-offset-8.step
          = image_tag "about_3.png"
          %p
            %span If you don’t you will make (expensive) wrong assumptions about your customers.
            Connecting with customers allows you to fix incorrect assumptions, while it's inexpensive to do so.

app/views/pages/contact_customer_care.html.haml
.section.contact-customer-care
  .container
    .well-hero.text-center
      %h1 Contact Customer Care
      %hr/
      .text-left
        %p 
          All members of our Customer Care team know Mount Dream inside-out.
          %br/
          We’ll get you an answer right away.
        %p You can also email us at #{mail_to "help@mountdream.com"}.
      %br/
      .text-left
        = form_tag do
          = text_field_tag 'name', nil, required: true, placeholder: "Your name",
            class: "text-field"
          = email_field_tag 'email', nil, required: true, placeholder: "Your email address",
            class: "text-field"
          = text_area 'message', nil, required: true, placeholder: "What can we help you with?",
            class: "text-area"

          = submit_tag "Submit ticket", class: "btn uppercase bold"
          

app/views/pages/help.html.haml
= render "shared/help_masthead"

.section.help-center
  .container
    .row
      .col-sm-9.main-content
      
        %h1 Popular Topics
        %hr/
        %br/
        
        .faq-tab.well
          %h2 
            Post an idea&nbsp;&nbsp;
            %i.glyphicon.glyphicon-chevron-down
          .questions
            .question
              %h4 How do I post an idea?
              %p You can start by filling out the form on the #{ link_to "post idea", post_idea_path } page. It’s quick and easy.
            .question
              %h4 Can I choose the questions that I ask members?
              %p Yes. Mount Dream Customer Care can suggest useful questions based on your idea and what you want to learn.
            .question
              %h4 Can I get feedback from a specific target market only?
              %p Yes, you can specify the target audience you want to reach. 
              %p As Mount Dream’s network grows, we can offer more and more precise targeting.
            .question
              %h4 How do I know my idea will not get stolen?
              %p Mount Dream does not guarantee that your idea will not get stolen. Nobody can make a claim like that in good faith. However, we believe we've created a safe environment for sharing ideas.
              %p Please visit our page on idea safety to learn more about this topic. Posting on Mount Dream is a personal choice and is not right for every person or idea.
            .question
              %h4 What is the cost of posting my idea?
              %p Mount Dream starts at $1 per response. You must purchase at least 25 responses.
              %p By adding questions and/or targeting specific markets, your price may increase up to $3 per response.
          
        .faq-tab.well
          %h2
            Give feedback on ideas&nbsp;&nbsp;
            %i.glyphicon.glyphicon-chevron-down
          .questions
            .question
              %h4 How do I start giving feedback on ideas?
              To start giving feedback, you can go to our #{ link_to "give feedback home page", give_feedback_path } and sign-up using Facebook or LinkedIn.
            .question
              %h4 Why can’t I register with just my email?
              %p We require login using Facebook or LinkedIn to enhance a sense of accountability on Mount Dream.
            .question
              %h4 How do I earn points?
              %p You earn points by giving quality feedback on ideas.
            .question
              %h4 How do you define quality feedback?
              %p Quality feedback has three characteristics:

              %ul
                %li Honest. The best way you can help an entrepreneur can be sharing what you don’t like about their idea.
                %li Thoughtful: Explaining the reasons why you feel the way you do, not simply stating “Good idea” or “I&nbsp;don’t like it”.
                %li Encouraging. Keeping an upbeat and positive attitude, especially when offering criticism.

              %p It may also be helpful to read about our #{ link_to "Culture & Values", about_path }, as our network is different from other networks.
              %p We are also looking for your opinion as a potential customer of the product or service, not as a business consultant.
            .question
              %h4 What do my points get me?
              %p You can redeem your points for products that were originally posted on Mount Dream.
          
        .faq-tab.well
          %h2
            Life after Mount Dream&nbsp;&nbsp;
            %i.glyphicon.glyphicon-chevron-down
          .questions
            .question
              %h4 Can I message back and forth with members who give me feedback?
              %p Yes.
              %h4 Can I message members who subscribe for a launch notification?
              %p When you are ready to launch, you can send up to three (3) messages to all users who subscribed for launch notifications. 
              %h4 What is the next step if I get positive results on my idea?
              %p It is now in your hands to execute your idea. Without execution, your idea is not worth anything. You have an idea that people want -- make the most of it.

      = render "shared/help_sidebar"

app/views/pages/home.html.haml
.home-masthead.text-center
  %h1 Pursue your&nbsp;dream, intelligently
  %h3
    Before you spend any more time and money on your business or product idea,
    %br{ class: "visible-md visible-lg" }/
    make sure customers actually want it.
  = link_to "Post Your Idea", post_idea_path, class: "btn btn-primary sharp"
.section.home-how-it-works.text-center
  .container
    %h1 How it Works
    .row
      .col-md-4
        = image_tag "icon_pitch.png", class: "icon"
        = image_tag "arrow_1.png", class: "arrow visible-lg visible-md"
        %h2 Record your pitch
        %p
          Record a simple video pitch
          %br{ class: "visible-md visible-lg" }/
          explaining your idea.
      .col-md-4
        = image_tag "icon_target_market.png", class: "icon"
        = image_tag "arrow_2.png", class: "arrow arrow_2 visible-lg visible-md"
        %h2 Select your target market
        %p 
          Select target audience you want
          %br{ class: "visible-md visible-lg" }/
          feedback from.
      .col-md-4
        = image_tag "icon_relax.png", class: "icon"
        %h2 Sit back and relax
        %p
          We'll distribute your pitch and gather
          %br{ class: "visible-lg" }/
          feedback for you.

.section.why-use-mount-dream.text-center
  .container
    %h1 Why use Mount Dream
    %br/
    %br/
    .col-md-6.image-wrapper
      = image_tag "home_why_use.png"
    .col-md-6.list-wrapper.text-left
      %ol.ol-circled
        %li
          %h2 Put your idea into action.
          %p Without action, an idea can go no where.
        %li
          %h2 Make sure your idea is good.
          %p Find out before spending lots of time or money.
        %li
          %h2 Better understand your potential&nbsp;customers.
          %p Make better decisions and reach success quicker.
        %li
          %h2 Show proof of market interest to investors.
          %p Add substance to your pitch.
        %li
          %h2 Line up potential customer.
          %p Generate revenue quickly or find beta testers.
        %li
          %h2 Get “outside the box” ideas.
          %p A wide variety of perspectives to enhance the value you bring customers.
        %li
          %h2 Passion comes from traction.
          %p Motivation comes from knowing that you are onto something.

.section.the-highest-quality-feedback.text-center
  .container
    %h1 The highest quality feedback, starting at $1 per&nbsp;response
    
    %h4 Focus groups will cost you thousands of dollars and the quality of the feedback is not guaranteed.
    = image_tag "home_quality_feedback.png"
    
    %h3 Our members provide feedback that is honest, thoughtful, and encouraging.
    %h4 100% Quality Response Guarantee. If a response is not useful, you don't pay for it.
    
.section.join-the-movement.text-center
  .container
    %h1 Join the Movement
    %br/
    .col-md-6.cta-box-wrapper
      .cta-box-teal.cta-box.text-left
        %h2 Pursue your&nbsp;dream
        %p The first step in living your dream is making sure customers see value in your idea.
        %br/
        = link_to "Post your idea", post_idea_path, class: "btn outline bold uppercase"
    .col-md-6.cta-box-wrapper
      .cta-box-red.cta-box.text-left
        %h2 Help someone pursue their&nbsp;dream
        %p Give honest, thoughtful and encouraging feedback on new business ideas, and earn points that can be redeemed for products from American entrepreneurs.
        %br/
        = link_to "Start giving feedback", "#", class: "btn outline bold uppercase"
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

app/views/pages/login.html.haml
.login-wrapper
  .login.container
    .well-hero.text-center
      %h1 Returning Users
      %hr/
      = render "shared/facebook_button"
      = render "shared/linkedin_button"
      %hr/
      %h3 New to Mount Dream?
      %p 
        Get started by
        %br{ class: "visible-xs" }/
        #{ link_to "joining our network for free", give_feedback_path }.

app/views/pages/post_idea.html.haml
.section.million-idea.text-center
  .container
    %h1 Think you&nbsp;have a&nbsp;$1,000,000&nbsp;idea?
    %h3 Don’t assume — get your idea in front of customers ASAP!

    .row
      .col-md-6.post-idea-video
        .video-wrapper
          <iframe src="https://player.vimeo.com/video/142270083" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        %p Watch our new commercial and learn why Mount Dream is <b>the perfect first step</b> for your business or product idea.

      .col-md-6.post-idea-form

        .form
          %h3.visible-xs.visible-sm Get&nbsp;started with&nbsp;Mount&nbsp;Dream right&nbsp;now
          = form_tag do
            = email_field_tag 'email', nil, required: true, placeholder: "Email",
              class: "field"
            = select_tag 'idea_type',
              options_for_select([['Type of idea', 1]], 1),
              class: "field"
            = select_tag 'idea_status', options_for_select([['Status of idea', 1]], 1), class: "field"
            = text_field_tag 'promocode', nil, required: false, placeholder: "Promo code",
              class: "field"

            = submit_tag "Continue »", class: "btn uppercase bold sharp"

        .well.hidden
          %h3 Congrats on taking the first step!
          %p A member of Mount Dream Customer Care will reach out to you with the next steps.
          %p In the meantime, start giving feedback on other ideas to get familiar with how Mount Dream works.
          = link_to "Start giving feedback", give_feedback_path, class: "btn uppercase bold"

.section-cta.text-center
  .container
    %h1 Got questions about posting your&nbsp;idea?
    %h4 Contact Mount Dream Customer Care today!
    = link_to "Submit ticket", contact_customer_care_path, class: "btn default uppercase bold"

app/views/shared/_facebook_button.html.haml
.login-btn-wrapper
  %i.fa.fa-facebook
  .divider
  = link_to "Continue with Facebook", "#", class: "btn sharp facebook"

app/views/shared/_footer.html.haml
.footer
  .footer-main
    .container
      .row
        .col-md-3.contact.text-center
          = link_to (image_tag "footer_logo.png", class: "footer-logo"), root_path
          %h4 Contact Customer Care
          %p
            Monday — Friday,
            %br{ class: "visible-lg visible-md" }/
            9 am — 5 pm EST
            %br/
            help@mountdream.com
            
        .col-md-6.text-center.footer-center
          .subscription
            %h4 Entrepreneurship&nbsp;tips and&nbsp;inspiration sent to&nbsp;your&nbsp;inbox
            = render "shared/subscription_form", label: "Subscribe now"
                
          %ul.social.list-inline
            %li
              = link_to "#" do
                %i.fa.fa-google-plus
            %li
              = link_to "#" do
                %i.fa.fa-facebook
            %li
              = link_to "#" do
                %i.fa.fa-twitter
            %li
              = link_to "#" do
                %i.fa.fa-youtube-play
            %li
              = link_to "#" do
                %i.fa.fa-instagram
                
          %ul.footer-navbar.list-inline
            %li= link_to "Home", root_url
            %li= link_to "Post idea", post_idea_path
            %li= link_to "About", about_path
            %li= link_to "Help", "#"
            %li= link_to "Blog", "#"
            %li= link_to "Press", "#"
            %li= link_to "Careers", "#"
        
        .col-md-3.kickstarter.text-center
          = link_to (image_tag "kickstarter_badge.png"), "https://www.kickstarter.com/projects/1027706210/mount-dream-a-pre-kickstarter-tool-launching-on-ki/description", target: "_blank"
        
  .footer-copy
    .container.text-center
      %p
        &copy; Copyright&nbsp;2015 Mount&nbsp;Dream. All&nbsp;Rights&nbsp;Reserved
        &nbsp;&middot;&nbsp;
        = link_to "Privacy", privacy_path
        &nbsp;&middot;&nbsp;
        = link_to "Terms", terms_path

app/views/shared/_header.html.haml
.header
  .navbar.navbar-fixed-top
    .container{ role: "navigation" }
      .navbar-header
        = link_to root_url do
          = image_tag "header_logo.png", class: "navbar-brand"
        %button.navbar-toggle.collapsed{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
      %ul.nav.navbar-nav.navbar-right.collapse.navbar-collapse
        %li= link_to "Login", login_path
        %li= link_to "About", about_path
        %li= link_to "Help", help_path
        %li= link_to "Got an idea?", post_idea_path, class: "btn btn-primary sharp"
        %li= link_to "Join for free", give_feedback_path, class: "btn default sharp"

app/views/shared/_help_breadcrumbs.html.haml
.help-breadcrumbs
  %p #{ link_to "Help Center", help_path } / Resource Name
  %hr/

app/views/shared/_help_masthead.html.haml
.help-masthead
  .container
    %h1 Help Center
    %h4 Have a question? We can help!

app/views/shared/_help_sidebar.html.haml
.col-sm-3.sidebar
  %hr{ class: "visible-xs" }/
  %nav.well.static
    %h3 Contact customer care
    %p 
      Need help? 
      %br{ class: "hidden-xs" }/
      We are available Monday&nbsp;—&nbsp;Friday, 9&nbsp;am&nbsp;—&nbsp;5&nbsp;pm&nbsp;EST.
    = link_to "Submit Ticket", contact_customer_care_path, class: "btn sharp uppercase bold"
    
    %p You can also email us at #{mail_to "help@mountdream.com"}.

    %h3 Other resources
    %ul
      %li
        = link_to "Idea Safety", idea_safety_path
      %li
        = link_to "Tips for Video Pitch", tips_for_video_path
      %li
        = link_to "Before You Post", before_you_post_path

app/views/shared/_linkedin_button.html.haml
.login-btn-wrapper
  %i.fa.fa-linkedin
  .divider
  = link_to "Continue with LinkedIn", "#", class: "btn sharp linkedin"